---
- name: Scrummage setup
  hosts: scrummageservers
  become: true
  tasks:
    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: download and launch a docker web container
      docker_container:
        name: gdag
        image: ghcr.io/matamorphosis/gdag:latest
        state: started
        restart_policy: always
        published_ports:
          - 8000:8000
          - 8080:8080

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes