name: publish

on: [push]

jobs:
  publish-scrummage-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Scrummage Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u matamorphosis --password-stdin
        docker build . --tag ghcr.io/matamorphosis/scrummage:latest
        docker push ghcr.io/matamorphosis/scrummage:latest
      env:
        CR_PAT: ${{ secrets.CR_PAT }}